name: Build and Deploy

on:
  push:
    branches:
      - test  # 监听 test 分支的推送

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7  # 或你需要的 Ruby 版本

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll Site in Desk Folder
        run: |
          cd desk  # 进入 desk 文件夹
          bundle exec jekyll build -d dist  # 将打包输出到 desk 下的 dist 文件夹

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cd desk/dist  # 进入 desk/dist 目录
          git init
          git add .
          git commit -m "Deploying Jekyll site to GitHub Pages"
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages
