name: Build and Deploy

on:
  push:
    branches:
      - test  # 替换成你的主分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7  # 替换成你需要的 Ruby 版本

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install
        
      - name: Build Jekyll Site
        run: |
          bundle exec jekyll build -d dist # 构建 Jekyll 网站

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cd dist
          git init
          git add .
          git commit -m "Deploying Jekyll site to GitHub Pages"
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages
